#!/usr/bin/env python3
"""Materialize a hard-linked, fully supervised view of an immutable subset.

The source subset is never modified. Rows with missing raster groups are excluded
from the derived manifest and recorded in view_provenance.json so training cannot
silently fail halfway through an epoch.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path
import shutil


GROUP_COLUMNS = (
    "label_path",
    "dem_path",
    "s1_t1_path",
    "s1_t2_path",
    "s1_change_path",
    "s1_qa_path",
    "s2_t1_path",
    "s2_t2_path",
    "s2_change_path",
    "s2_qa_path",
    "masks_path",
)


def _link(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if destination.stat().st_ino != source.stat().st_ino:
            raise RuntimeError(f"View already contains a different file: {destination}")
        return
    os.link(source, destination)


def materialize(source_root: Path, output_root: Path) -> dict[str, object]:
    source_root = source_root.expanduser().resolve(strict=True)
    output_root = output_root.expanduser().resolve()
    manifest_path = source_root / "metadata" / "training_manifest.csv"
    if not manifest_path.is_file():
        raise FileNotFoundError(manifest_path)
    with manifest_path.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
        fieldnames = list(rows[0]) if rows else []
    if not rows:
        raise RuntimeError("Source manifest is empty")

    selected: list[dict[str, str]] = []
    excluded: list[dict[str, object]] = []
    for row in rows:
        missing = [column for column in GROUP_COLUMNS if not (source_root / row[column]).is_file()]
        if missing:
            excluded.append({"sample_id": row["sample_id"], "split": row["split"], "missing": missing})
        else:
            selected.append(row)

    output_root.mkdir(parents=True, exist_ok=True)
    for row in selected:
        for column in GROUP_COLUMNS:
            relative = Path(row[column])
            _link(source_root / relative, output_root / relative)

    metadata_out = output_root / "metadata"
    metadata_out.mkdir(parents=True, exist_ok=True)
    with (metadata_out / "training_manifest.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(selected)
    # Retain the source subset metadata as provenance inputs; the derived manifest
    # and train-only normalization are regenerated by the audit/stats tools.
    for source in (source_root / "metadata").glob("*.json"):
        shutil.copy2(source, metadata_out / source.name)
    provenance = {
        "schema_version": "1.0",
        "source_root": str(source_root),
        "source_manifest": str(manifest_path),
        "source_rows": len(rows),
        "selected_rows": len(selected),
        "excluded_rows": len(excluded),
        "selected_counts": {
            split: sum(row["split"] == split for row in selected)
            for split in ("train", "val", "test")
        },
        "excluded_by_split": {
            split: sum(row["split"] == split for row in excluded)
            for split in ("train", "val", "test")
        },
        "exclusion_rule": "all manifest raster groups must exist; no pixel values or labels are synthesized",
        "excluded_samples": excluded,
    }
    (metadata_out / "view_provenance.json").write_text(
        json.dumps(provenance, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return provenance


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args()
    provenance = materialize(args.source_root, args.output_root)
    print(json.dumps({key: provenance[key] for key in ("source_rows", "selected_rows", "excluded_rows", "selected_counts", "excluded_by_split")}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
